export default {
  // Currency List
  START_WEBSOCKET_SUBSCRIPTION: "START_WEBSOCKET_SUBSCRIPTION",
  START_WEBSOCKET_SUBSCRIPTION_SUCCESS: "START_WEBSOCKET_SUBSCRIPTION_SUCCESS",
  START_WEBSOCKET_SUBSCRIPTION_FAIL: "START_WEBSOCKET_SUBSCRIPTION_FAIL",
  STOP_WEBSOCKET_SUBSCRIPTION: "STOP_WEBSOCKET_SUBSCRIPTION",
  UPDATE_CURRENCY_LIST_ITEM_PRICE: "UPDATE_CURRENCY_LIST_ITEM_PRICE",

  // Converter
  REQUEST_EXCHANGE_RATE: "REQUEST_EXCHANGE_RATE",
  REQUEST_EXCHANGE_RATE_SUCCESS: "REQUEST_EXCHANGE_RATE_SUCCESS",
  REQUEST_EXCHANGE_RATE_FAIL: "REQUEST_EXCHANGE_RATE_FAIL",
  SELECT_FROM_CURRENCY: "SELECT_FROM_CURRENCY",
  CHANGE_FROM_VALUE: "CHANGE_FROM_VALUE",
  SELECT_TO_CURRENCY: "SELECT_TO_CURRENCY",
  CHANGE_TO_VALUE: "CHANGE_TO_VALUE"
};
