export default {
  START_WEBSOCKET_SUBSCRIPTION: "START_WEBSOCKET_SUBSCRIPTION",
  START_WEBSOCKET_SUBSCRIPTION_SUCCESS: "START_WEBSOCKET_SUBSCRIPTION_SUCCESS",
  START_WEBSOCKET_SUBSCRIPTION_FAIL: "START_WEBSOCKET_SUBSCRIPTION_FAIL",
  STOP_WEBSOCKET_SUBSCRIPTION: "STOP_WEBSOCKET_SUBSCRIPTION",
  UPDATE_CURRENCY_LIST_ITEM_PRICE: "UPDATE_CURRENCY_LIST_ITEM_PRICE"
};
